WebUI/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebUI.DAL;

namespace WebUI.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        private AppDbContext _context { get; set; }
        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async  Task<IViewComponentResult> InvokeAsync()
        {
            var model=await _context.Settings.ToDictionaryAsync(s => s.Key, s => s.Value);
            return View(model);
        }
    }
}

WebUI/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebUI.DAL;

namespace WebUI.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        private AppDbContext _context { get; }
        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model= await _context.Settings.ToDictionaryAsync(s => s.Key, s => s.Value);
            return View(model);
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
@using WebUI.Services
@inject SettingService settingServices;
@{ 
    Dictionary<string, string> setting = settingServices.GetAllSettings();
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="icon" href="img/favicon.png" sizes="192x192" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="~/owlcarousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/owlcarousel/owl.theme.default.min.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Fiorello &#8211; A Flower Shop and Florist WooCommerce Theme</title>
</head>

<body>
    @await Component.InvokeAsync("Header") 
    @RenderBody()
    @await Component.InvokeAsync("Footer")

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/e5e249fce2.js" crossorigin="anonymous"></script>
    <script src="~/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/js/script.js"></script>
</body>

</html>